version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
